"""
Common Data Structures & Interfaces for UGV Autonomous Navigation
Ensures clean, strongly-typed contracts between perception, localization, mapping, planning, and control.
"""

from dataclasses import dataclass, field
from typing import List, Tuple, Optional
import numpy as np


@dataclass
class Pose2D:
    """Represents 2D state of the UGV in world coordinates (meters and radians)."""
    x: float = 0.0          # X position in world frame (meters)
    y: float = 0.0          # Y position in world frame (meters)
    theta: float = 0.0      # Heading angle in radians, standard [-pi, pi], 0 = along +X axis

    def as_tuple(self) -> Tuple[float, float, float]:
        return (self.x, self.y, self.theta)

    def position_tuple(self) -> Tuple[float, float]:
        return (self.x, self.y)

    def copy(self) -> "Pose2D":
        return Pose2D(x=self.x, y=self.y, theta=self.theta)


@dataclass
class TwistCommand:
    """Velocity command sent to differential drive controller / motor actuators."""
    linear_v: float = 0.0   # Desired forward velocity in m/s
    angular_w: float = 0.0  # Desired yaw angular velocity in rad/s


@dataclass
class CameraFrame:
    """Represents a single optical sensor frame (simulated or hardware USB/CSI camera)."""
    image: np.ndarray       # RGB / BGR image (Height x Width x 3) uint8
    depth: Optional[np.ndarray] = None  # Optional depth map in meters (Height x Width) float32
    timestamp: float = 0.0  # Acquisition timestamp in seconds
    fov_deg: float = 70.0   # Horizontal field of view in degrees


@dataclass
class ObstacleRegion:
    """Represents a single detected obstacle object in image and local ground coordinates."""
    bbox: Tuple[int, int, int, int]  # (bx, by, bw, bh) in pixel coordinates
    center_u: float
    bottom_v: float
    distance_meters: float           # Estimated distance to front edge (meters)
    local_x: float                   # Estimated obstacle center forward relative to UGV (meters)
    local_y: float                   # Estimated obstacle center left relative to UGV (meters)
    radius_meters: float             # Estimated physical radius (meters)
    confidence: float = 1.0
    label: str = "obstacle"


@dataclass
class ObstacleDetection:
    """Enriched perception output containing masks, annotated frames, and local metric obstacles."""
    local_points: List[Tuple[float, float]] = field(default_factory=list)  # (x_forward, y_left) relative to UGV
    obstacle_regions: List[ObstacleRegion] = field(default_factory=list)
    obstacle_mask: Optional[np.ndarray] = None      # Binary obstacle mask (H, W) uint8
    traversable_mask: Optional[np.ndarray] = None   # Binary traversable ground mask (H, W) uint8
    annotated_image: Optional[np.ndarray] = None    # RGB image with bounding boxes & HUD telemetry
    confidence: float = 1.0
    timestamp: float = 0.0


@dataclass
class GridMap:
    """2D Discrete Occupancy Grid Map."""
    data: np.ndarray        # 2D numpy array (height_cells, width_cells), values 0 (free) to 100 (occupied), -1 unknown
    resolution: float       # Size of each cell in meters (e.g., 0.15m)
    origin_x: float = 0.0   # World X coordinate corresponding to cell (0, 0)
    origin_y: float = 0.0   # World Y coordinate corresponding to cell (0, 0)

    @property
    def width_cells(self) -> int:
        return self.data.shape[1]

    @property
    def height_cells(self) -> int:
        return self.data.shape[0]

    @property
    def width_meters(self) -> float:
        return self.width_cells * self.resolution

    @property
    def height_meters(self) -> float:
        return self.height_cells * self.resolution


@dataclass
class Path2D:
    """Sequence of 2D waypoints generated by path planner in world coordinates."""
    waypoints: List[Tuple[float, float]] = field(default_factory=list)  # [(x0, y0), (x1, y1), ...]
    is_valid: bool = False
    timestamp: float = 0.0

    def is_empty(self) -> bool:
        return len(self.waypoints) == 0
